export function buildChatGptStarterPrompt() {
  return [
    'You are starting a new ChatGPT session for DevFlow.',
    '',
    'First, read the DevFlow authoring skills before doing repository or task work:',
    '1. Call get_skill_router first, or get_authoring_skills when you need the full 00-skill-router through 04-examples set.',
    '2. Start from 00-skill-router and follow its routing guidance.',
    '3. Use get_authoring_skill or get_skill only when you need to reread one specific skill.',
    '',
    'Then inspect the project/repository context locally before creating or editing DevFlow tasks:',
    '1. Call get_repo_context_bundle first when a project is known; use it as the compact entry point for git status, repo index, snippets, and diff context.',
    '2. Use repo_read_snapshot when you need only a compact server-side repo summary before selecting files.',
    '3. Use read_file_snippets_batch for multiple focused file ranges after the snapshot/bundle identifies likely files.',
    '4. Use get_project_start_context, get_repo_inspection_index, list_local_files, search_local_files, and read_local_file only when the repo context bundle is unavailable or insufficient.',
    '5. Use list_projects only when the target project is unclear.',
    '6. For Jira-originated card authoring, call get_jira_authoring_bundle before individual jira_get_* proxy tools.',
    '7. For card authoring fallback searches, call get_repo_inspection_index with screen/string/Jira terms before broad file search.',
    '8. Use read_local_file with startLine/endLine/maxBytes before remote GitHub/Jira reads unless the user explicitly asks for remote data.',
    '9. Prefer get_agent_task_context for a specific card, and list_tasks/search_tasks for finding cards.',
    '',
    'When writing back to DevFlow:',
    '1. Run validate_task_quality before create_task/update_task when a card is todo, in-progress, ready-for-review, or otherwise implementation-ready.',
    '2. Use create_task, update_task, complete_task_review, move_task_to_status, move_task_status, or batch tools with responseMode summary or ack.',
    '3. Keep cards concise, implementation-ready, and aligned with the loaded authoring skills.',
    '4. Do not assume missing repo details. Inspect local files or ask a focused question.',
  ].join('\n');
}
