export const VALID_AGENTS = ['Codex', 'Antigravity', 'Claude'];
export const VALID_EFFORTS = ['none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'];
export const VALID_MODELS = [
  'GPT-5.5', 'GPT-5.4', 'GPT-5.4 Mini',
  'Gemini 3.5 Flash', 'Gemini 3.1 Pro',
  'Claude 4.8 Opus', 'Claude 4.7 Opus', 'Claude 4.6 Opus', 'Claude 4.6 Sonnet',
];
export const VALID_STATUSES = ['backlog', 'todo', 'in-progress', 'ready-for-review', 'done'];
export const VALID_PRIORITIES = ['low', 'medium', 'high'];

export const TASK_SCHEMA_DEF = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Task or Batch Task Payload',
  type: 'object',
  description: "When creating tasks via API, DO NOT send 'id' or 'displayId'. The backend will generate them automatically. You can send a single Task object, an array of Tasks, or a nested structure { parent: Task, children: Task[] }.",
  properties: {
    id: { type: 'string', description: "READ-ONLY. Generated by backend. Do NOT send during creation." },
    displayId: { type: 'string', description: "READ-ONLY. Generated by backend. Do NOT send during creation." },
    projectId: { type: 'string', description: 'Project ID this task belongs to' },
    title: { type: 'string', description: 'Title of the task' },
    description: { type: 'string', description: 'Detailed description of the task (Markdown)' },
    status: {
      type: 'string',
      enum: VALID_STATUSES,
      description: 'Current status of the task',
    },
    branch: { type: 'string', description: 'Git branch name associated with this task' },
    priority: {
      type: 'string',
      enum: VALID_PRIORITIES,
      description: 'Priority level',
    },
    tags: {
      type: 'array',
      items: { type: 'string' },
      description: 'List of tags/labels',
    },
    targetFiles: {
      type: 'array',
      items: { type: 'string' },
      description: 'Files relevant to the task',
    },
    checklist: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          text: { type: 'string' },
          completed: { type: 'boolean' },
        },
        required: ['id', 'text', 'completed'],
      },
      description: 'Sub-tasks or checklist items',
    },
    designImages: { type: 'array', items: { type: 'string' }, maxItems: 5, description: 'Array of up to 5 URLs or base64 strings to design mockups or images' },
    specUrl: { type: 'string', description: 'URL to a specification document' },
    agent: {
      type: 'string',
      enum: VALID_AGENTS,
      description: "AI Agent assigned to the task. If this is a subtask (parentId is provided), this MUST match the parent task's agent.",
    },
    model: {
      type: 'string',
      enum: VALID_MODELS,
      description: 'AI Model used for processing',
    },
    effort: {
      type: 'string',
      enum: VALID_EFFORTS,
      description: 'Estimated reasoning effort required',
    },
    parentId: { type: 'string', description: "ID of the parent task if this is a subtask. If provided, the agent property must match the parent's agent." },
    reasoning: { type: 'string', description: 'Reasoning or context for this task' },
    acceptanceCriteria: { type: 'string', description: 'Criteria for accepting the task as done' },
    verification: { type: 'string', description: 'Steps to verify the task' },
    repoContext: { type: 'string', description: 'Context about the repository' },
    jiraKey: { type: 'string', description: 'Jira Issue Key associated with this task' },
    repo: { type: 'string', description: 'Repository URL' },
    sourceUrl: { type: 'string', description: 'Original source URL of the task' },
    createdAt: { type: 'string', format: 'date-time' },
    updatedAt: { type: 'string', format: 'date-time' },
    logs: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          timestamp: { type: 'string', format: 'date-time' },
          message: { type: 'string' },
          type: { type: 'string' },
        },
        required: ['id', 'timestamp', 'message', 'type'],
      },
    },
  },
  required: ['title', 'projectId'],
};
